# Generated by Django 3.2.2 on 2021-05-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
