# Generated by Django 3.2.2 on 2021-06-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medApp', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.CharField(max_length=20)),
                ('title', models.TextField(default='')),
                ('authors', models.TextField(default='')),
                ('abstract', models.TextField(default='')),
                ('keywords', models.TextField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
